"""add users

Revision ID: 0dd62348d802
Revises: d58354cdc36d
Create Date: 2026-04-07 18:10:17.344535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd62348d802'
down_revision: Union[str, Sequence[str], None] = 'd58354cdc36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('master_password_hash', sa.String(), nullable=False))
    op.drop_column('users', 'username')
    op.drop_column('users', 'leak_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leak_source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'master_password_hash')
    # ### end Alembic commands ###
